version: 1
build:
  # Do skip OCD3 build. Initializer reference build is made through GitHub Actions.
  bash_commands: "exit 0"
deploy:
  # Do not deploy via OCD3. Initializer publishing is done via GitHub Actions.
  bash_commands: "exit 0"